[[Blosc2]]
arch = "aarch64"
git-tree-sha1 = "66883b0caf0eed5522d965c040e7f3a61335ffa7"
os = "macos"

    [[Blosc2.download]]
    sha256 = "3366df53a25d62af79319af6289430b9e2d8f56f1b6599f25a44700f9f457740"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.aarch64-apple-darwin.tar.gz"
[[Blosc2]]
arch = "aarch64"
git-tree-sha1 = "b19b2f52563d830dff95be7f4054ad1cec4984a1"
libc = "glibc"
os = "linux"

    [[Blosc2.download]]
    sha256 = "a9c5af48caf208426aad699c5993fb8db68f7233a59c5409ce8f353cbad5103c"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.aarch64-linux-gnu.tar.gz"
[[Blosc2]]
arch = "aarch64"
git-tree-sha1 = "6c77573b1cb706a0271f3b2f5affa435579515c2"
libc = "musl"
os = "linux"

    [[Blosc2.download]]
    sha256 = "c8d400ef959593fa5b38d5560edb94658e220366b5ad3fc8c859354a778afad4"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.aarch64-linux-musl.tar.gz"
[[Blosc2]]
arch = "aarch64"
git-tree-sha1 = "ae0ac53338a7f913296db6b6ba4f658bb1bbb4b9"
os = "freebsd"

    [[Blosc2.download]]
    sha256 = "1fc0d3c4c0f756cd332054b72d8891161467bb4a365fddfce07f91a2d806d2c9"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.aarch64-unknown-freebsd.tar.gz"
[[Blosc2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "68f677ae6ec75029d1986ac7b787f1a09a1d57d6"
libc = "glibc"
os = "linux"

    [[Blosc2.download]]
    sha256 = "8f5c7b211e2deb8170a9433ce9c9b1ecc26c68bcb465c0a337bdb3a021a66458"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.armv6l-linux-gnueabihf.tar.gz"
[[Blosc2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "95f5701ac1adde49c41d43f0ddf8473dec918147"
libc = "musl"
os = "linux"

    [[Blosc2.download]]
    sha256 = "1f0416334bcc6f19738555e9f417ef368e0cae456c9f85256cdbc8b2729b0473"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.armv6l-linux-musleabihf.tar.gz"
[[Blosc2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0b87dcefbfa2aaea83de504ff6839a4a40e7a75d"
libc = "glibc"
os = "linux"

    [[Blosc2.download]]
    sha256 = "6949a10cfc72bf0eb391be7f204e08ac6d0947eca931c378aaed92dba5c969c9"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.armv7l-linux-gnueabihf.tar.gz"
[[Blosc2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f0424af77f04346e92897959a208bb1d73df4099"
libc = "musl"
os = "linux"

    [[Blosc2.download]]
    sha256 = "a4a96c7061403cbf6aa2fdc16a33209d63899fed75d78ce066d6d619dcd7b535"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.armv7l-linux-musleabihf.tar.gz"
[[Blosc2]]
arch = "i686"
git-tree-sha1 = "94b60034d0a3c9937528fea867d006c0f273be7a"
libc = "glibc"
os = "linux"

    [[Blosc2.download]]
    sha256 = "427d06af7e381139b88cc94cf531cc9d3b3d98b26170f09874f4b0259b05cfc4"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.i686-linux-gnu.tar.gz"
[[Blosc2]]
arch = "i686"
git-tree-sha1 = "debdb03c5d8586f56753e947ba02b3f1521e3d5a"
libc = "musl"
os = "linux"

    [[Blosc2.download]]
    sha256 = "04fcad2d0536caba581fe1b5286baf69ed7fd51aa56f2959ccf74fd79e812389"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.i686-linux-musl.tar.gz"
[[Blosc2]]
arch = "i686"
git-tree-sha1 = "c671e510a18cd92d870948c86f00714fe857710d"
os = "windows"

    [[Blosc2.download]]
    sha256 = "173ff3c5675eb40461b9a2a62af995167d28b8a1274c28c35133ffa90ad29f85"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.i686-w64-mingw32.tar.gz"
[[Blosc2]]
arch = "powerpc64le"
git-tree-sha1 = "3de7477b577a09080a041603bbf173d61a990f41"
libc = "glibc"
os = "linux"

    [[Blosc2.download]]
    sha256 = "fce749c0c1840b2ab57675b68badc3ab7036c291e746b922899db55ddfd9b25e"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.powerpc64le-linux-gnu.tar.gz"
[[Blosc2]]
arch = "riscv64"
git-tree-sha1 = "5547a9f3154e18a34804de2e3a9f8fef80ac8511"
libc = "glibc"
os = "linux"

    [[Blosc2.download]]
    sha256 = "75aa4070455d42a7014fb0a83e8c55865e213a8fa7bd7e8df67f895cff1bba10"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.riscv64-linux-gnu.tar.gz"
[[Blosc2]]
arch = "x86_64"
git-tree-sha1 = "a3ea747f77cc3794435fe9fd7e2d5852853b9ee6"
os = "macos"

    [[Blosc2.download]]
    sha256 = "2811f39a0893b29597cdb449b9d34b996c8ded40a87997d57e308ef1012c68b3"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.x86_64-apple-darwin.tar.gz"
[[Blosc2]]
arch = "x86_64"
git-tree-sha1 = "67307ac27ef4dea7243b0e59c392b567a6c227cb"
libc = "glibc"
os = "linux"

    [[Blosc2.download]]
    sha256 = "cd7e9e770eeb74b59355c307e55e2a550a0cf42733b2a660f0669afcc44d4d37"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.x86_64-linux-gnu.tar.gz"
[[Blosc2]]
arch = "x86_64"
git-tree-sha1 = "f3847940b2867739027d005bde9c5ea6b056b721"
libc = "musl"
os = "linux"

    [[Blosc2.download]]
    sha256 = "63ecb97bf9e2aa023176b7cd96ded8011b84bb13c21d5da79df975e8ae0d4850"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.x86_64-linux-musl.tar.gz"
[[Blosc2]]
arch = "x86_64"
git-tree-sha1 = "5b8c113920cd84712a4d2377edff3e3e00fede56"
os = "freebsd"

    [[Blosc2.download]]
    sha256 = "50c4bb61cfe66f489c0a15e60e187213b900103f89ea24abdd133a594e0eb424"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.x86_64-unknown-freebsd.tar.gz"
[[Blosc2]]
arch = "x86_64"
git-tree-sha1 = "97ef932af96d4375f53b5706761f7c739a31c402"
os = "windows"

    [[Blosc2.download]]
    sha256 = "2932861d23117cbc5bc232c95650478e76e5e5db1ff725f7cea638413052f96e"
    url = "https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl/releases/download/Blosc2-v202.2300.0+0/Blosc2.v202.2300.0.x86_64-w64-mingw32.tar.gz"
